name: device_sound_profile
description: My new Flutter plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    platforms:
      android:
        default_package: device_sound_profile_android
      ios:
        default_package: device_sound_profile_ios

dependencies:
  flutter:
    sdk: flutter
  device_sound_profile_android:
    path: ../device_sound_profile_android
  device_sound_profile_ios:
    path: ../device_sound_profile_ios
  device_sound_profile_platform_interface:
    path: ../device_sound_profile_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
