name: device_sound_profile_plugin
repository: https://github.com/developersailor/device_sound_profile_plugin
packages:
  - device_sound_profile
  - device_sound_profile_ios
  - device_sound_profile_android
  - device_sound_profile_platform_interface
scripts:
  prepare: melos bootstrap && melos run build
  analyze:
    exec: dart analyze .
  format:
    exec: dart format .
  build:
    exec: dart run build_runner build --delete-conflicting-outputs

ide:
  intellij:
    enabled: false
